# Generated by Django 4.1.3 on 2022-11-20 21:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(choices=[(15, '15 Minuite'), (30, '30 Minuite'), (45, '45 Minuite'), (60, '1 Hour')], default=30)),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 week of lessons.'), django.core.validators.MaxValueValidator(limit_value=4, message='Interval cannot be more than a month.')])),
                ('teacher', models.CharField(max_length=100)),
                ('no_of_lessons', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 lesson.'), django.core.validators.MaxValueValidator(limit_value=50, message='Cannot book more than 50 lessons.')])),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=200)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 lesson.'), django.core.validators.MaxValueValidator(limit_value=50, message='Cannot book more than 50 lessons.')])),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 week of lessons.'), django.core.validators.MaxValueValidator(limit_value=4, message='Interval cannot be more than a month.')])),
                ('duration', models.IntegerField(choices=[(15, '15 Minuite'), (30, '30 Minuite'), (45, '45 Minuite'), (60, '1 Hour')], default=30)),
                ('topic', models.CharField(blank=True, default='Any', max_length=50)),
                ('teacher', models.CharField(blank=True, default='Any', max_length=100)),
                ('status', models.CharField(default='In Progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
