# Generated by Django 4.1.3 on 2022-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='director status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
    ]
