# Generated by Django 4.1.3 on 2022-11-12 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 lesson.'), django.core.validators.MaxValueValidator(limit_value=50, message='Cannot book more than 50 lessons.')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 week of lessons.'), django.core.validators.MaxValueValidator(limit_value=4, message='Interval cannot be more than a month.')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='teacher',
            field=models.CharField(blank=True, default='Any', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='topic',
            field=models.CharField(blank=True, default='Any', max_length=50),
        ),
    ]
