# Generated by Django 4.1.3 on 2022-11-14 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_request_status_alter_request_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField(choices=[(15, '15 Minuite'), (30, '30 Minuite'), (45, '45 Minuite'), (60, '1 Hour')], default=30)),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must book at least 1 week of lessons.'), django.core.validators.MaxValueValidator(limit_value=4, message='Interval cannot be more than a month.')])),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('no_of_lessons', models.IntegerField(default=1)),
            ],
        ),
    ]
