# Generated by Django 4.1.3 on 2022-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_request_status_alter_request_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.DateTimeField(),
        ),
    ]
