# Generated by Django 4.1.3 on 2022-11-23 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_booking_duration_alter_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 12, 40, 11, 575130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 12, 40, 11, 575282, tzinfo=datetime.timezone.utc)),
        ),
    ]
