# Generated by Django 4.1.3 on 2022-11-15 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_request_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 Minute'), (30, '30 Minute'), (45, '45 Minute'), (60, '1 Hour')], default=30),
        ),
    ]
