# Generated by Django 3.2.12 on 2022-11-26 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20221124_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 17, 16, 26, 190680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 17, 16, 26, 190840, tzinfo=utc)),
        ),
    ]
