# Generated by Django 4.1.3 on 2022-11-15 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_request_availability_alter_request_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='availability',
        ),
        migrations.AddField(
            model_name='request',
            name='day',
            field=models.DateField(default=datetime.date(2022, 11, 15)),
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
