# Generated by Django 4.1.3 on 2022-11-15 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_request_availability_request_day_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 18, 39, 0, 341785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 15, 18, 39, 0, 341943, tzinfo=datetime.timezone.utc)),
        ),
    ]
