# Generated by Django 4.1.3 on 2022-11-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_request_day_alter_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='day',
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 18, 30, 53, 889694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 16, 18, 30, 53, 889881, tzinfo=datetime.timezone.utc)),
        ),
    ]
