# Generated by Django 4.1.3 on 2022-11-16 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_request_day_request_date_alter_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 16)),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(18, 52, 36, 595611)),
        ),
    ]
